# Generated by Django 4.1 on 2022-09-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="desciption",
            new_name="description",
        ),
    ]
