# Generated by Django 4.1.1 on 2022-09-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=150)),
                ("ALias", models.CharField(max_length=200)),
                ("Sexo", models.CharField(max_length=50)),
                ("Power_And_Skills", models.CharField(max_length=400)),
                ("Image", models.URLField(blank=True)),
                ("Family", models.CharField(max_length=200)),
            ],
        ),
    ]
