# Generated by Django 4.1.1 on 2022-09-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="ALias",
            new_name="Alias",
        ),
    ]
